//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.PhotographicSpecimens = new HashSet<PhotographicSpecimen>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.DateTime CatalogDate { get; set; }
        public string Notes { get; set; }
        public int CollectionId { get; set; }
        public int AuthorId { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual Author Author { get; set; }
        public virtual ICollection<PhotographicSpecimen> PhotographicSpecimens { get; set; }
    }
}
