//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArquivoSilvaMagalhaes.Resources.DataStrings", typeof(DataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História administrativa e biográfica.
        /// </summary>
        public static string AdministrativeAndBiographicStory {
            get {
                return ResourceManager.GetString("AdministrativeAndBiographicStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História do arquivo.
        /// </summary>
        public static string ArchiveHistory {
            get {
                return ResourceManager.GetString("ArchiveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missão do arquivo.
        /// </summary>
        public static string ArchiveMission {
            get {
                return ResourceManager.GetString("ArchiveMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição de anexos.
        /// </summary>
        public static string AttachmentsDescriptions {
            get {
                return ResourceManager.GetString("AttachmentsDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número original.
        /// </summary>
        public static string AuthorCatalogCode {
            get {
                return ResourceManager.GetString("AuthorCatalogCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza o primeiro nome do autor.
        /// </summary>
        public static string AuthorFirstNamePrompt {
            get {
                return ResourceManager.GetString("AuthorFirstNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza o último nome do autor.
        /// </summary>
        public static string AuthorLastNamePrompt {
            get {
                return ResourceManager.GetString("AuthorLastNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string AvailableAuthors {
            get {
                return ResourceManager.GetString("AvailableAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção.
        /// </summary>
        public static string AvailableCollections {
            get {
                return ResourceManager.GetString("AvailableCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto do banner.
        /// </summary>
        public static string BannerTexts {
            get {
                return ResourceManager.GetString("BannerTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biografia.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de catalogação.
        /// </summary>
        public static string CatalogationDate {
            get {
                return ResourceManager.GetString("CatalogationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de coleção.
        /// </summary>
        public static string CatalogCode {
            get {
                return ResourceManager.GetString("CatalogCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificação.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificações.
        /// </summary>
        public static string Classifications {
            get {
                return ResourceManager.GetString("Classifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleções.
        /// </summary>
        public static string Collection__Collections {
            get {
                return ResourceManager.GetString("Collection__Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensão da coleção.
        /// </summary>
        public static string CollectionDimension {
            get {
                return ResourceManager.GetString("CollectionDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logótipo da coleção.
        /// </summary>
        public static string CollectionLogo {
            get {
                return ResourceManager.GetString("CollectionLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da coleção.
        /// </summary>
        public static string CollectionName {
            get {
                return ResourceManager.GetString("CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de coleção.
        /// </summary>
        public static string CollectionType {
            get {
                return ResourceManager.GetString("CollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção.
        /// </summary>
        public static string CollectionType_Collection {
            get {
                return ResourceManager.GetString("CollectionType_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundo.
        /// </summary>
        public static string CollectionType_Fond {
            get {
                return ResourceManager.GetString("CollectionType_Fond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro tipo de coleção.
        /// </summary>
        public static string CollectionType_Other {
            get {
                return ResourceManager.GetString("CollectionType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes de contacto.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto visível.
        /// </summary>
        public static string ContactVisible {
            get {
                return ResourceManager.GetString("ContactVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordenadas.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação sobre direitos de autor.
        /// </summary>
        public static string CopyrightInfo {
            get {
                return ResourceManager.GetString("CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de criação.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currículo.
        /// </summary>
        public static string Curriculum {
            get {
                return ResourceManager.GetString("Curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de criação.
        /// </summary>
        public static string DateOfCreation {
            get {
                return ResourceManager.GetString("DateOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de falecimento.
        /// </summary>
        public static string DeathDate {
            get {
                return ResourceManager.GetString("DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensão.
        /// </summary>
        public static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do documento.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização do documento.
        /// </summary>
        public static string DocumentLocation {
            get {
                return ResourceManager.GetString("DocumentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        public static string DocumentType_Image {
            get {
                return ResourceManager.GetString("DocumentType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro.
        /// </summary>
        public static string DocumentType_Other {
            get {
                return ResourceManager.GetString("DocumentType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string DocumentType_Text {
            get {
                return ResourceManager.GetString("DocumentType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vídeo.
        /// </summary>
        public static string DocumentType_Video {
            get {
                return ResourceManager.GetString("DocumentType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final.
        /// </summary>
        public static string EndMoment {
            get {
                return ResourceManager.GetString("EndMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final Produção.
        /// </summary>
        public static string EndProductionDate {
            get {
                return ResourceManager.GetString("EndProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de evento.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de validade.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Âmbito e conteúdo.
        /// </summary>
        public static string FieldAndContents {
            get {
                return ResourceManager.GetString("FieldAndContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficheiro a guardar.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do ficheiro.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do ficheiro.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro nome.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos relacionados.
        /// </summary>
        public static string HasAttachments {
            get {
                return ResourceManager.GetString("HasAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem marcas ou carimbos.
        /// </summary>
        public static string HasMarksOrStamps {
            get {
                return ResourceManager.GetString("HasMarksOrStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabeçalho.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar após expirar.
        /// </summary>
        public static string HideAfterExpiry {
            get {
                return ResourceManager.GetString("HideAfterExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de produção da imagem.
        /// </summary>
        public static string Image__ProductionDate {
            get {
                return ResourceManager.GetString("Image__ProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexação.
        /// </summary>
        public static string Indexation {
            get {
                return ResourceManager.GetString("Indexation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial Produção.
        /// </summary>
        public static string InitialProductionDate {
            get {
                return ResourceManager.GetString("InitialProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da intervenção.
        /// </summary>
        public static string InterventionDescription {
            get {
                return ResourceManager.GetString("InterventionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É fixo.
        /// </summary>
        public static string IsPermanent {
            get {
                return ResourceManager.GetString("IsPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É link util.
        /// </summary>
        public static string IsUsefulLink {
            get {
                return ResourceManager.GetString("IsUsefulLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visível ao público.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-chave.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavras-chave.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Idioma.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da última modificação.
        /// </summary>
        public static string LastModificationDate {
            get {
                return ResourceManager.GetString("LastModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de última alteração.
        /// </summary>
        public static string LastModifiedDate {
            get {
                return ResourceManager.GetString("LastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último nome.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logotipo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização do logotipo.
        /// </summary>
        public static string LogoLocation {
            get {
                return ResourceManager.GetString("LogoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato do ficheiro.
        /// </summary>
        public static string MimeFormat {
            get {
                return ResourceManager.GetString("MimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidade.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem classificação.
        /// </summary>
        public static string NoClassification {
            get {
                return ResourceManager.GetString("NoClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organização original.
        /// </summary>
        public static string OrganizationSystem {
            get {
                return ResourceManager.GetString("OrganizationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de parceria.
        /// </summary>
        public static string PartnershipType {
            get {
                return ResourceManager.GetString("PartnershipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de produção.
        /// </summary>
        public static string ProductionDate {
            get {
                return ResourceManager.GetString("ProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveniência.
        /// </summary>
        public static string Provenience {
            get {
                return ResourceManager.GetString("Provenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicação.
        /// </summary>
        public static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de publicação.
        /// </summary>
        public static string PublicationDate {
            get {
                return ResourceManager.GetString("PublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de publicação.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string ReferencedLink {
            get {
                return ResourceManager.GetString("ReferencedLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de remoção.
        /// </summary>
        public static string RemotionDate {
            get {
                return ResourceManager.GetString("RemotionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de remoção.
        /// </summary>
        public static string RemovalDate {
            get {
                return ResourceManager.GetString("RemovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do responsável.
        /// </summary>
        public static string ResponsibleName {
            get {
                return ResourceManager.GetString("ResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de digitalização.
        /// </summary>
        public static string ScanDate {
            get {
                return ResourceManager.GetString("ScanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processo de digitalização.
        /// </summary>
        public static string ScanProcess {
            get {
                return ResourceManager.GetString("ScanProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário.
        /// </summary>
        public static string ShowcasePhoto_Comment {
            get {
                return ResourceManager.GetString("ShowcasePhoto_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de e-mail do comentador.
        /// </summary>
        public static string ShowcasePhoto_CommenterEmail {
            get {
                return ResourceManager.GetString("ShowcasePhoto_CommenterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do comentador.
        /// </summary>
        public static string ShowcasePhoto_CommenterName {
            get {
                return ResourceManager.GetString("ShowcasePhoto_CommenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de e-mail visível.
        /// </summary>
        public static string ShowcasePhoto_IsEmailVisible {
            get {
                return ResourceManager.GetString("ShowcasePhoto_IsEmailVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string SiteLink {
            get {
                return ResourceManager.GetString("SiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destaque.
        /// </summary>
        public static string SpotLight {
            get {
                return ResourceManager.GetString("SpotLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial.
        /// </summary>
        public static string StartMoment {
            get {
                return ResourceManager.GetString("StartMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição estado conservação.
        /// </summary>
        public static string StateDetailed {
            get {
                return ResourceManager.GetString("StateDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação estado conservação.
        /// </summary>
        public static string StateSimple {
            get {
                return ResourceManager.GetString("StateSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento.
        /// </summary>
        public static string TechnicalDocument_DocumentType {
            get {
                return ResourceManager.GetString("TechnicalDocument_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        public static string TextContent {
            get {
                return ResourceManager.GetString("TextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de upload.
        /// </summary>
        public static string UploadDate {
            get {
                return ResourceManager.GetString("UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de carregamento.
        /// </summary>
        public static string UploadedDate {
            get {
                return ResourceManager.GetString("UploadedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho para imagem.
        /// </summary>
        public static string UriPath {
            get {
                return ResourceManager.GetString("UriPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço do video.
        /// </summary>
        public static string UriPathVideo {
            get {
                return ResourceManager.GetString("UriPathVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação sobre visitantes.
        /// </summary>
        public static string VisitorInformation {
            get {
                return ResourceManager.GetString("VisitorInformation", resourceCulture);
            }
        }
    }
}
