//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArquivoSilvaMagalhaes.Resources.DataStrings", typeof(DataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biografia.
        /// </summary>
        public static string AuthorBiography {
            get {
                return ResourceManager.GetString("AuthorBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento.
        /// </summary>
        public static string AuthorBirthDate {
            get {
                return ResourceManager.GetString("AuthorBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum.
        /// </summary>
        public static string AuthorCurriculum {
            get {
                return ResourceManager.GetString("AuthorCurriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de falecimento.
        /// </summary>
        public static string AuthorDeathDate {
            get {
                return ResourceManager.GetString("AuthorDeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro nome.
        /// </summary>
        public static string AuthorFirstName {
            get {
                return ResourceManager.GetString("AuthorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último nome.
        /// </summary>
        public static string AuthorLastName {
            get {
                return ResourceManager.GetString("AuthorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidade.
        /// </summary>
        public static string AuthorNationality {
            get {
                return ResourceManager.GetString("AuthorNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensão da coleção.
        /// </summary>
        public static string CollectionDimension {
            get {
                return ResourceManager.GetString("CollectionDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem classificação.
        /// </summary>
        public static string NoClassification {
            get {
                return ResourceManager.GetString("NoClassification", resourceCulture);
            }
        }
    }
}
