//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Models.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CollectionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CollectionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArquivoSilvaMagalhaes.Models.Translations.CollectionStrings", typeof(CollectionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História administrativa e biográfica.
        /// </summary>
        public static string AdministrativeAndBiographicStory {
            get {
                return ResourceManager.GetString("AdministrativeAndBiographicStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código de coleção tem que ser alfanumérico. (0-9, A-Z, a-z).
        /// </summary>
        public static string AlphanumericCode {
            get {
                return ResourceManager.GetString("AlphanumericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição de anexos.
        /// </summary>
        public static string AttachmentDescription {
            get {
                return ResourceManager.GetString("AttachmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoria de.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de referência.
        /// </summary>
        public static string CatalogCode {
            get {
                return ResourceManager.GetString("CatalogCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações sobre direitos de autor.
        /// </summary>
        public static string CopyrightInfo {
            get {
                return ResourceManager.GetString("CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar coleção.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar coleção.
        /// </summary>
        public static string DeleteTitleFormat {
            get {
                return ResourceManager.GetString("DeleteTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende eliminar esta coleção? Todos os documentos (e elementos associados a estes) serão eliminados!.
        /// </summary>
        public static string DeleteWarningMessage {
            get {
                return ResourceManager.GetString("DeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da coleção.
        /// </summary>
        public static string DetailsTitleFormat {
            get {
                return ResourceManager.GetString("DetailsTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensão.
        /// </summary>
        public static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos desta coleção.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar coleção.
        /// </summary>
        public static string EditTitleFormat {
            get {
                return ResourceManager.GetString("EditTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de fim de produção.
        /// </summary>
        public static string EndProductionDate {
            get {
                return ResourceManager.GetString("EndProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleções.
        /// </summary>
        public static string EntityNamePlural {
            get {
                return ResourceManager.GetString("EntityNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Âmbito e conteúdo.
        /// </summary>
        public static string FieldAndContents {
            get {
                return ResourceManager.GetString("FieldAndContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem anexos.
        /// </summary>
        public static string HasAttachments {
            get {
                return ResourceManager.GetString("HasAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de início de produção.
        /// </summary>
        public static string InitialProductionDate {
            get {
                return ResourceManager.GetString("InitialProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visível ao público.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota: Se a coleção não estiver visível ao público, quaisquer documentos ou imagens (mesmo se forem públicos) não serão listados no site nem aparecerão em resultados de pesquisa..
        /// </summary>
        public static string IsVisibleHint {
            get {
                return ResourceManager.GetString("IsVisibleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logótipo.
        /// </summary>
        public static string LogoLocation {
            get {
                return ResourceManager.GetString("LogoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É recomendado uma imagem .jpg ou .png com dimensões de 400x400. A imagem é opcional..
        /// </summary>
        public static string LogoRecommendation {
            get {
                return ResourceManager.GetString("LogoRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de organização.
        /// </summary>
        public static string OrganizationSystem {
            get {
                return ResourceManager.GetString("OrganizationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de produção.
        /// </summary>
        public static string ProductionPeriod {
            get {
                return ResourceManager.GetString("ProductionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveniência.
        /// </summary>
        public static string Provenience {
            get {
                return ResourceManager.GetString("Provenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traduções desta coleção.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de coleção.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção.
        /// </summary>
        public static string Type_Collection {
            get {
                return ResourceManager.GetString("Type_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundo.
        /// </summary>
        public static string Type_Fond {
            get {
                return ResourceManager.GetString("Type_Fond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro.
        /// </summary>
        public static string Type_Other {
            get {
                return ResourceManager.GetString("Type_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma coleção com este código de catalogação..
        /// </summary>
        public static string Validation_CodeAlreadyExists {
            get {
                return ResourceManager.GetString("Validation_CodeAlreadyExists", resourceCulture);
            }
        }
    }
}
