//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Models.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArquivoSilvaMagalhaes.Models.Translations.DocumentStrings", typeof(DocumentStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotógrafo.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de catalogação.
        /// </summary>
        public static string CatalogationDate {
            get {
                return ResourceManager.GetString("CatalogationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de referência.
        /// </summary>
        public static string CatalogCode {
            get {
                return ResourceManager.GetString("CatalogCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um documento com este código de referência. Escolha outro..
        /// </summary>
        public static string CodeAlreadyExists {
            get {
                return ResourceManager.GetString("CodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do código do documento tem que respeitar o seguinte formato: Coleção-Documento (Ex: ASM-1 ou PAS-002).
        /// </summary>
        public static string CodeFormat {
            get {
                return ResourceManager.GetString("CodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção deste documento.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar documento.
        /// </summary>
        public static string CreateTitleFormat {
            get {
                return ResourceManager.GetString("CreateTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar documento.
        /// </summary>
        public static string DeleteTitleFormat {
            get {
                return ResourceManager.GetString("DeleteTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende eliminar este documento? Todas as imagens associadas a este serão removidas!.
        /// </summary>
        public static string DeleteWarningMessage {
            get {
                return ResourceManager.GetString("DeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do documento.
        /// </summary>
        public static string DetailsTitleFormat {
            get {
                return ResourceManager.GetString("DetailsTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do documento.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização do documento.
        /// </summary>
        public static string DocumentLocation {
            get {
                return ResourceManager.GetString("DocumentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar documento.
        /// </summary>
        public static string EditTitleFormat {
            get {
                return ResourceManager.GetString("EditTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        public static string EntityNamePlural {
            get {
                return ResourceManager.GetString("EntityNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Âmbito e Conteúdo.
        /// </summary>
        public static string FieldAndContents {
            get {
                return ResourceManager.GetString("FieldAndContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem que primeiro escolher uma coleção..
        /// </summary>
        public static string MustChooseCollection {
            get {
                return ResourceManager.GetString("MustChooseCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do responsável.
        /// </summary>
        public static string ResponsibleName {
            get {
                return ResourceManager.GetString("ResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do documento.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data desconhecida.
        /// </summary>
        public static string UnknownDocumentDate {
            get {
                return ResourceManager.GetString("UnknownDocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de catalogação não pode ser anterior à data do documento..
        /// </summary>
        public static string Validation_CataloguedBeforeExisted {
            get {
                return ResourceManager.GetString("Validation_CataloguedBeforeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de catalogação não pode ser posterior à data atual..
        /// </summary>
        public static string Validation_CataloguedInTheFuture {
            get {
                return ResourceManager.GetString("Validation_CataloguedInTheFuture", resourceCulture);
            }
        }
    }
}
