//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Models.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArquivoSilvaMagalhaes.Models.Translations.ImageStrings", typeof(ImageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma imagem com esse código de referência. Escolha outro..
        /// </summary>
        public static string CodeAlreadyExists {
            get {
                return ResourceManager.GetString("CodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código da imagem tem que seguir o seguinte formato:  Coleção-Documento-Imagem (Ex: ASM-001-002 ou PAS-1-20).
        /// </summary>
        public static string CodeFormat {
            get {
                return ResourceManager.GetString("CodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar imagem.
        /// </summary>
        public static string CreateTitleFormat {
            get {
                return ResourceManager.GetString("CreateTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento desta imagem.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar imagem.
        /// </summary>
        public static string EditTitleFormat {
            get {
                return ResourceManager.GetString("EditTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagens.
        /// </summary>
        public static string EntityNamePlural {
            get {
                return ResourceManager.GetString("EntityNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de referência.
        /// </summary>
        public static string ImageCode {
            get {
                return ResourceManager.GetString("ImageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visível ao público.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexações desta imagem.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem que primeiro escolher um documento..
        /// </summary>
        public static string MustChooseDocument {
            get {
                return ResourceManager.GetString("MustChooseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de produção.
        /// </summary>
        public static string ProductionDate {
            get {
                return ResourceManager.GetString("ProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicação.
        /// </summary>
        public static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
