//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Models.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpecimenStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecimenStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArquivoSilvaMagalhaes.Models.Translations.SpecimenStrings", typeof(SpecimenStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add digital photographs.
        /// </summary>
        public static string AddPhotos {
            get {
                return ResourceManager.GetString("AddPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The annotation must only contain digits and letters..
        /// </summary>
        public static string ArchivalCodeFormat {
            get {
                return ResourceManager.GetString("ArchivalCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        public static string ArchivalReferenceCode {
            get {
                return ResourceManager.GetString("ArchivalReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original code.
        /// </summary>
        public static string AuthorCatalogationCode {
            get {
                return ResourceManager.GetString("AuthorCatalogationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specimen with that reference code already exists. Please choose another one..
        /// </summary>
        public static string CodeAlreadyExists {
            get {
                return ResourceManager.GetString("CodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference code must respect the following format: Collection-Document-Image-Specimen. The annotation is inserted into a different field, and no special characters are allowed..
        /// </summary>
        public static string CodeFormat {
            get {
                return ResourceManager.GetString("CodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add specimen.
        /// </summary>
        public static string CreateTitleFormat {
            get {
                return ResourceManager.GetString("CreateTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete specimen.
        /// </summary>
        public static string DeleteTitleFormat {
            get {
                return ResourceManager.GetString("DeleteTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this specimen?.
        /// </summary>
        public static string DeleteWarningMessage {
            get {
                return ResourceManager.GetString("DeleteWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conservation state description.
        /// </summary>
        public static string DetailedStateDescription {
            get {
                return ResourceManager.GetString("DetailedStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specimen details.
        /// </summary>
        public static string DetailsTitleFormat {
            get {
                return ResourceManager.GetString("DetailsTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit specimen.
        /// </summary>
        public static string EditTitleFormat {
            get {
                return ResourceManager.GetString("EditTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specimen.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specimens.
        /// </summary>
        public static string EntityNamePlural {
            get {
                return ResourceManager.GetString("EntityNamePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta imagem não existe..
        /// </summary>
        public static string Error_UnknownImage {
            get {
                return ResourceManager.GetString("Error_UnknownImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has marks or stamps.
        /// </summary>
        public static string HasMarksOrStamps {
            get {
                return ResourceManager.GetString("HasMarksOrStamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention description.
        /// </summary>
        public static string InterventionDescription {
            get {
                return ResourceManager.GetString("InterventionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose an image first..
        /// </summary>
        public static string MustChooseImage {
            get {
                return ResourceManager.GetString("MustChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No digital photographs..
        /// </summary>
        public static string NoDigitalPhotographs {
            get {
                return ResourceManager.GetString("NoDigitalPhotographs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital photographs.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographic process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference code.
        /// </summary>
        public static string ReferenceCode {
            get {
                return ResourceManager.GetString("ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conservation state.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string State_1 {
            get {
                return ResourceManager.GetString("State_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediocre.
        /// </summary>
        public static string State_2 {
            get {
                return ResourceManager.GetString("State_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfactory.
        /// </summary>
        public static string State_3 {
            get {
                return ResourceManager.GetString("State_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string State_4 {
            get {
                return ResourceManager.GetString("State_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string State_5 {
            get {
                return ResourceManager.GetString("State_5", resourceCulture);
            }
        }
    }
}
