//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionText
    {
        public CollectionText()
        {
            this.LanguageCode = "pt";
        }
    
        public int Id { get; set; }
        public string LanguageCode { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Provenience { get; set; }
        public string AdministrativeAndBiographicStory { get; set; }
        public string Dimension { get; set; }
        public string FieldAndContents { get; set; }
        public string CopyrightInfo { get; set; }
        public int CollectionId { get; set; }
    
        public virtual Collection Collection { get; set; }
    }
}
