//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public Collection()
        {
            this.CollectionTexts = new HashSet<CollectionText>();
            this.Documents = new HashSet<Document>();
            this.Authors = new HashSet<Author>();
        }
    
        public int Id { get; set; }
        public CollectionType Type { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string LogoLocation { get; set; }
        public bool HasAttachments { get; set; }
        public string OrganizationSystem { get; set; }
        public string Notes { get; set; }
        public bool IsVisible { get; set; }
        public string CatalogCode { get; set; }
    
        public virtual ICollection<CollectionText> CollectionTexts { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
    }
}
