//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    
    public enum CollectionType : byte
    {
        Regular = 1,
        Background = 2,
        Other = 3
    }
}
