//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalPhotograph
    {
        public DigitalPhotograph()
        {
            this.ShowcasePhotos = new HashSet<ShowcasePhoto>();
        }
    
        public int Id { get; set; }
        public string ScanDate { get; set; }
        public string StoreLocation { get; set; }
        public string Process { get; set; }
        public string CopyrightInfo { get; set; }
        public string IsVisible { get; set; }
        public int SpecimenId { get; set; }
    
        public virtual ICollection<ShowcasePhoto> ShowcasePhotos { get; set; }
        public virtual Specimen Specimen { get; set; }
    }
}
