//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentTexts = new HashSet<DocumentText>();
            this.Keywords = new HashSet<Keyword>();
            this.Specimen = new HashSet<Specimen>();
        }
    
        public int Id { get; set; }
        public string ResponsibleName { get; set; }
        public string DocumentDate { get; set; }
        public System.DateTime CatalogationDate { get; set; }
        public string Notes { get; set; }
        public int CollectionId { get; set; }
        public int AuthorId { get; set; }
        public string CatalogCode { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual ICollection<DocumentText> DocumentTexts { get; set; }
        public virtual Author Author { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
        public virtual ICollection<Specimen> Specimen { get; set; }
    }
}
