//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentText
    {
        public DocumentText()
        {
            this.LanguageCode = "pt";
        }
    
        public int Id { get; set; }
        public string LanguageCode { get; set; }
        public string DocumentLocation { get; set; }
        public string FieldAndContents { get; set; }
        public string Description { get; set; }
        public int DocumentId { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
