//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EspolioTesteContainer : DbContext
    {
        public EspolioTesteContainer()
            : base("name=EspolioTesteContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collection> CollectionSet { get; set; }
        public virtual DbSet<CollectionText> CollectionTextSet { get; set; }
        public virtual DbSet<Document> DocumentSet { get; set; }
        public virtual DbSet<DocumentText> DocumentTextSet { get; set; }
        public virtual DbSet<Author> AuthorSet { get; set; }
        public virtual DbSet<AuthorText> AuthorTextSet { get; set; }
        public virtual DbSet<Keyword> KeywordSet { get; set; }
        public virtual DbSet<KeywordText> KeywordTextSet { get; set; }
        public virtual DbSet<Specimen> SpecimenSet { get; set; }
        public virtual DbSet<SpecimenText> SpecimenTextSet { get; set; }
        public virtual DbSet<Format> FormatSet { get; set; }
        public virtual DbSet<Process> ProcessSet { get; set; }
        public virtual DbSet<ProcessText> ProcessTextSet { get; set; }
        public virtual DbSet<Classification> ClassificationSet { get; set; }
        public virtual DbSet<ClassificationText> ClassificationTextSet { get; set; }
        public virtual DbSet<DigitalPhotograph> DigitalPhotographSet { get; set; }
        public virtual DbSet<ShowcasePhoto> ShowcasePhotoSet { get; set; }
        public virtual DbSet<ShowcasePhotoText> ShowcasePhotoTextSet { get; set; }
    }
}
