//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowcasePhoto
    {
        public ShowcasePhoto()
        {
            this.ShowcasePhotoTexts = new HashSet<ShowcasePhotoText>();
        }
    
        public int Id { get; set; }
        public string CommenterName { get; set; }
        public string CommenterEmail { get; set; }
        public string IsEmailVisible { get; set; }
        public string VisibleSince { get; set; }
        public int DigitalPhotographId { get; set; }
    
        public virtual DigitalPhotograph DigitalPhotograph { get; set; }
        public virtual ICollection<ShowcasePhotoText> ShowcasePhotoTexts { get; set; }
    }
}
