//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes.Sandbox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specimen
    {
        public Specimen()
        {
            this.SpecimenTexts = new HashSet<SpecimenText>();
            this.Classification = new HashSet<Classification>();
            this.DigitalPhotographs = new HashSet<DigitalPhotograph>();
        }
    
        public int Id { get; set; }
        public string CatalogCode { get; set; }
        public string AuthorCatalogationCode { get; set; }
        public bool HasMarksOrStamps { get; set; }
        public string Indexation { get; set; }
        public string Notes { get; set; }
        public int FormatId { get; set; }
        public int DocumentId { get; set; }
    
        public virtual ICollection<SpecimenText> SpecimenTexts { get; set; }
        public virtual Format Format { get; set; }
        public virtual Document Document { get; set; }
        public virtual Process Process { get; set; }
        public virtual ICollection<Classification> Classification { get; set; }
        public virtual ICollection<DigitalPhotograph> DigitalPhotographs { get; set; }
    }
}
