//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquivoSilvaMagalhaes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotographicSpecimen
    {
        public PhotographicSpecimen()
        {
            this.KeyWords = new HashSet<KeyWord>();
            this.DigitalPhotos = new HashSet<DigitalPhoto>();
        }
    
        public int Id { get; set; }
        public string AuthorCode { get; set; }
        public string Notes { get; set; }
        public string InterventionDescription { get; set; }
        public string Topic { get; set; }
        public System.DateTime SpecimenDate { get; set; }
    
        public virtual PhotographicProcess PhotographicProcess { get; set; }
        public virtual PhotographicFormat PhotographicFormat { get; set; }
        public virtual Document Document { get; set; }
        public virtual ICollection<KeyWord> KeyWords { get; set; }
        public virtual ICollection<DigitalPhoto> DigitalPhotos { get; set; }
    }
}
